### ISSUE TITLE
变量改动后没有生成影响信息

### ISSUE THREAD

**Issue by jackqdldd** [baikaishuipp/jcci#10]
<img width="580" alt="294ee47670be7a3d67118abcb89b9a20" src="https://github.com/baikaishuipp/jcci/assets/168320760/ce266903-0aed-4418-a7df-61e21e476e3d">
这两个值变量都改了，结果文件的links里面只有第二个变量，没有第一个变量

**Comment by baikaishuipp** [comment]
@jackqdldd 使用bug/fix试一下，
