### ISSUE TITLE
xml文件中一个函数有改动，但是结果文件中缺失该函数

### ISSUE THREAD

**Issue by liuhuoer** [baikaishuipp/jcci#12]

**Comment by liuhuoer** [comment]
![IMG_20240511_100722](https://github.com/baikaishuipp/jcci/assets/34497588/53be554c-54f9-4b88-a1ab-2fa183f40524)

**Comment by liuhuoer** [comment]
![IMG_20240511_100732](https://github.com/baikaishuipp/jcci/assets/34497588/ac57466b-bc1a-49fa-85c7-694a46d87dd8)
![Uploading IMG_20240511_100722.jpg…]()

**Comment by baikaishuipp** [comment]
已修复，请用beta分支再试
