### ISSUE TITLE
jcci运行疑似中断，查表阶段卡住了

### ISSUE THREAD

**Issue by liuhuoer** [baikaishuipp/jcci#15]
** 描述问题 **
jcci运行疑似中断，查表阶段卡住，后续不再打日志，持续几天也没终止。

** 提供信息 **
1. JCCI的版本/分支main分支/f97822fbde236aded99e6bd9719cb8bc9e86712f
2. python 的版本3.9.0
3. 控制台日志文件：

**Comment by liuhuoer** [comment]
![IMG_20240604_091216](https://github.com/baikaishuipp/jcci/assets/34497588/5700a6f5-9e4f-4ee6-8971-06744aaa0123)
![IMG_20240604_091321](https://github.com/baikaishuipp/jcci/assets/34497588/76a23e8c-8c49-4fad-8d41-7ef905d131c7)

**Comment by baikaishuipp** [comment]
与#16 同一个问题
