### ISSUE TITLE
在部分项目运行过程中存在运行时长过长问题

### ISSUE THREAD

**Issue by liuhuoer** [baikaishuipp/jcci#16]
** 描述问题 **
改动文件仅4个文件，jcci运行时长5h+。

** 提供信息 **
1. JCCI的版本/分支main/5fd172810f5df4f1561fd40d731a4141b1d7e19b
2. python 的版本python3.9.0

**Comment by baikaishuipp** [comment]
项目总体有多少文件

**Comment by baikaishuipp** [comment]
已修复，graph计算最长路径陷入循环
