### ISSUE TITLE
需要增加controller 继承接口的问题

### ISSUE THREAD

**Issue by lujiaqi** [baikaishuipp/jcci#17]
** 描述问题 **
1.controller extend 接口, 注解路径都在接口里. 无法找到
** 提供信息 **
<img width="659" alt="image" src="https://github.com/baikaishuipp/jcci/assets/5178323/2bda7bac-d057-4ddf-8b49-f8845c08eace">
<img width="751" alt="image" src="https://github.com/baikaishuipp/jcci/assets/5178323/d30ff73e-183f-47e6-8434-a264b56de282">

**Comment by baikaishuipp** [comment]
Fixed，已合到main分支
