### ISSUE TITLE
调用链与实际不符

### ISSUE THREAD

**Issue by liuhuoer** [baikaishuipp/jcci#18]
** 描述问题 **
调用链在项目代码中和实际调用关系有差异，具体如图
** 提供信息 **
1. JCCI的版本/分支master6月4拉取的版本
2. python 的版本3.9.0
3. A->B链路断了反馈：当前A节点截图、类名(com.XXX.XX.AClass)，调用A节点的B方法截图（包含调用A地方)、类名(com.XXX.XX.BClass)、B方法节点的method_invocation_map：（select method_invocation_map from methods where method_name='B')

![IMG_20240614_111515](https://github.com/baikaishuipp/jcci/assets/34497588/d1a139fb-9f27-4fe8-9291-ac7c812d9960)

5. 控制台日志文件

**Comment by baikaishuipp** [comment]
不是问题
