### ISSUE TITLE
analyze_two_commit  币对规则,是全局检索对比么，我看好像不是针对变更的 diff 文件分析

### ISSUE THREAD

**Issue by HakunamatataLeo** [baikaishuipp/jcci#28]
** 描述问题 **

** 提供信息 **
1. JCCI的版本/分支
2. python 的版本
3. A->B链路断了反馈：当前A节点截图、类名(com.XXX.XX.AClass)，调用A节点的B方法截图（包含调用A地方)、类名(com.XXX.XX.BClass)、B方法节点的method_invocation_map：（select method_invocation_map from methods where method_name='B')
4. 控制台日志文件

**Comment by HakunamatataLeo** [comment]
@baikaishuipp

**Comment by baikaishuipp** [comment]
是基于变更进行分析的
