### ISSUE TITLE
method_invocation_map解析方法参数类型错误

### ISSUE THREAD

**Issue by zhangchao1028** [baikaishuipp/jcci#31]
** 描述问题 **
我发现当方法参数是对象.get方法时，method_invocation_map解析出来的使用方法，只能获取参数对象是对象，并不是对象.get方法的真实参数类
** 提供信息 **
1. master分支
2. python 3.8
3. 我发现当方法参数是对象.get方法时，method_invocation_map解析出来的使用方法，只能获取参数对象是对象，并不是对象.get方法的真实参数类
4. 影响： 因为controller里解析到method_invocation_map类型不对，导致真正修改了这个controller调用的service这个方法时，controller识别不到变化，因为controller里识别到的method_invocation_map的参数类型是对象，不是long。
截图：
<img width="939" alt="image" src="https://github.com/user-attachments/assets/80d8f098-82a1-42c1-bf6e-4f5d6300b8cd">
<img width="1418" alt="image" src="https://github.com/user-attachments/assets/b8871bd3-fdfa-4bf6-993d-246f09e43be7">

<img width="502" alt="image" src="https://github.com/user-attachments/assets/6d9937ff-808f-45d9-a94c-af504388ba26">

5. 控制台日志文件
<img width="1708" alt="image" src="https://github.com/user-attachments/assets/c890489b-e779-4ab4-b1c0-c10b48ea218c">

**Comment by baikaishuipp** [comment]
未复现此问题
