### ISSUE TITLE
解析class method method_invocation_map中entity实体时，缺失包路径名称

### ISSUE THREAD

**Issue by zhangchao1028** [baikaishuipp/jcci#32]
** 描述问题 **

** 提供信息 **
1. Master分支
2. python 的版本 3.8
3. 帮看看：我的class引入对象时，import 了 entity.*，在解析class method method_invocation_map的entity时，对象路径缺少完整的包路径，导致调用链分析不准
4. 控制台日志文件

<img width="802" alt="image" src="https://github.com/user-attachments/assets/ddaaf04a-ee55-434a-8031-6210a692e131">
<img width="1053" alt="image" src="https://github.com/user-attachments/assets/5c8bf117-667d-4bf0-b538-4aec9d984878">

<img width="346" alt="image" src="https://github.com/user-attachments/assets/44184f6e-61ec-42c6-a2e9-8de63c4b1fc9">

**Comment by baikaishuipp** [comment]
改下checkstyle, import 按需引入
