### ISSUE TITLE
changed_declar = [decl['name'] for decl in diff_result_item.impact[java_file_class_path]['declarators']] KeyError: 'name'

### ISSUE THREAD

**Issue by cjh20130613** [baikaishuipp/jcci#6]
分析commitd差异化报错，使用的是https://gitee.com/youlaiorg/youlai-cloud.git这个项目，master分支，commitId1:1146b37,commitid：5e66c11
报错信息指向：changed_declar = [decl['name'] for decl in diff_result_item.impact[java_file_class_path]['declarators']]
 KeyError: 'name'

**Comment by baikaishuipp** [comment]
本地试了没有报错，请提供jcci版本或微信联系我
![image](https://github.com/baikaishuipp/jcci/assets/16160694/9da74188-50a3-4bb2-ac0a-6a6c25d47dd5)
