### ISSUE TITLE
Hi, do you konw this error "xml.etree.ElementTree.ParseError: no element found: line 1, column 0" in  "tree = ET.ElementTree(ET.fromstring(xml_content))"

### ISSUE THREAD

**Issue by cat1437-6** [baikaishuipp/jcci#7]
Hi, do you konw this error "xml.etree.ElementTree.ParseError: no element found: line 1, column 0" in  "tree = ET.ElementTree(ET.fromstring(xml_content))"

**Comment by baikaishuipp** [comment]
Can you provide specific code information and screenshots?
