### ISSUE TITLE
 'MethodInvocation' object has no attribute 'type'

### ISSUE THREAD

**Issue by ryanlove** [baikaishuipp/jcci#9]
执行analyze_two_commit 报错

**Comment by ryanlove** [comment]
已初始化环境
pip3 install javalang 
pip3 install unidiff


 File "/Users/ryan/workspace/Autohome/ahoh/jcci/jcci/src/jcci/java_parse.py", line 524, in _deal_type
    elif argument.type is not None:
AttributeError: 'MethodInvocation' object has no attribute 'type'

**Comment by baikaishuipp** [comment]
已俢复，请用bug/fix 再验证下这个问题
